import type { Question } from '../types'

/**
 * Original reasoning puzzles, written for Quotient.
 * None are taken from real IQ tests (Raven's, WAIS, Mensa, etc. are copyrighted).
 * To add your own, copy any object below and change the fields. Keep answers exact.
 */

export const questions: Question[] = [
  // ---------- EASY ----------
  {
    id: 'seq-e1',
    category: 'sequence',
    difficulty: 'easy',
    type: 'multiple-choice',
    prompt: 'What number comes next?\n\n2, 4, 6, 8, __',
    options: ['9', '10', '12', '14'],
    answer: '10',
    explanation: 'The numbers go up by 2 each time, so 8 + 2 = 10.',
  },
  {
    id: 'ana-e1',
    category: 'analogy',
    difficulty: 'easy',
    type: 'multiple-choice',
    prompt: 'Hot is to Cold as Up is to __',
    options: ['Sky', 'Down', 'High', 'Top'],
    answer: 'Down',
    explanation: 'Each pair is a set of opposites. The opposite of Up is Down.',
  },
  {
    id: 'odd-e1',
    category: 'odd-one-out',
    difficulty: 'easy',
    type: 'multiple-choice',
    prompt: 'Which one does not belong?',
    options: ['Apple', 'Banana', 'Carrot', 'Grape'],
    answer: 'Carrot',
    explanation: 'Apple, banana and grape are fruits. A carrot is a vegetable.',
  },
  {
    id: 'seq-e2',
    category: 'sequence',
    difficulty: 'easy',
    type: 'multiple-choice',
    prompt: 'What letter comes next?\n\nA, B, C, D, __',
    options: ['E', 'F', 'G', 'Z'],
    answer: 'E',
    explanation: 'These are letters in order, so D is followed by E.',
  },
  {
    id: 'num-e1',
    category: 'numerical',
    difficulty: 'easy',
    type: 'short-answer',
    prompt: 'You have 3 boxes. Each box holds 4 apples. How many apples in total?',
    answer: '12',
    explanation: '3 boxes × 4 apples = 12 apples.',
  },

  // ---------- MEDIUM ----------
  {
    id: 'seq-m1',
    category: 'sequence',
    difficulty: 'medium',
    type: 'multiple-choice',
    prompt: 'What number comes next?\n\n3, 6, 12, 24, __',
    options: ['30', '36', '48', '60'],
    answer: '48',
    explanation: 'Each number doubles: 24 × 2 = 48.',
  },
  {
    id: 'ana-m1',
    category: 'analogy',
    difficulty: 'medium',
    type: 'multiple-choice',
    prompt: 'Finger is to Hand as Leaf is to __',
    options: ['Green', 'Branch', 'Tree', 'Root'],
    answer: 'Tree',
    explanation: 'A finger is a part of a hand, just as a leaf is a part of a tree.',
  },
  {
    id: 'logic-m1',
    category: 'logic',
    difficulty: 'medium',
    type: 'multiple-choice',
    prompt: 'All cats are mammals. Felix is a cat.\n\nTherefore, Felix is a __',
    options: ['Dog', 'Mammal', 'Bird', 'Fish'],
    answer: 'Mammal',
    explanation: 'If every cat is a mammal and Felix is a cat, Felix must be a mammal.',
  },
  {
    id: 'odd-m1',
    category: 'odd-one-out',
    difficulty: 'medium',
    type: 'multiple-choice',
    prompt: 'Which shape does not belong?',
    options: ['Square', 'Circle', 'Triangle', 'Cube'],
    answer: 'Cube',
    explanation: 'Square, circle and triangle are flat (2D) shapes. A cube is solid (3D).',
  },
  {
    id: 'seq-m2',
    category: 'sequence',
    difficulty: 'medium',
    type: 'multiple-choice',
    prompt: 'What letter comes next?\n\nA, C, E, G, __',
    options: ['H', 'I', 'J', 'K'],
    answer: 'I',
    explanation: 'The pattern skips one letter each time (A, _, C, _, E…), so after G comes I.',
  },
  {
    id: 'num-m1',
    category: 'numerical',
    difficulty: 'medium',
    type: 'short-answer',
    prompt: 'A shirt costs $20 after a 50% discount. What was its original price (in dollars)?',
    answer: '40',
    explanation: 'A 50% discount halves the price, so the original was $20 × 2 = $40.',
  },

  // ---------- HARD ----------
  {
    id: 'seq-h1',
    category: 'sequence',
    difficulty: 'hard',
    type: 'multiple-choice',
    prompt: 'What number comes next?\n\n1, 1, 2, 3, 5, 8, __',
    options: ['11', '12', '13', '15'],
    answer: '13',
    explanation: 'Each number is the sum of the two before it (5 + 8 = 13). This is the Fibonacci sequence.',
  },
  {
    id: 'seq-h2',
    category: 'sequence',
    difficulty: 'hard',
    type: 'multiple-choice',
    prompt: 'What number comes next?\n\n2, 3, 5, 7, 11, __',
    options: ['12', '13', '14', '15'],
    answer: '13',
    explanation: 'These are prime numbers (divisible only by 1 and themselves). The next prime after 11 is 13.',
  },
  {
    id: 'ana-h1',
    category: 'analogy',
    difficulty: 'hard',
    type: 'multiple-choice',
    prompt: '8 is to 4 as 18 is to __',
    options: ['6', '9', '12', '14'],
    answer: '9',
    explanation: 'The second number is half the first: 8 → 4, so 18 → 9.',
  },
  {
    id: 'logic-h1',
    category: 'logic',
    difficulty: 'hard',
    type: 'multiple-choice',
    prompt: 'Mary is taller than Jane. Jane is taller than Sue.\n\nWho is the shortest?',
    options: ['Mary', 'Jane', 'Sue', "Can't tell"],
    answer: 'Sue',
    explanation: 'Mary > Jane > Sue in height, so Sue is the shortest.',
  },
  {
    id: 'num-h1',
    category: 'numerical',
    difficulty: 'hard',
    type: 'short-answer',
    prompt: 'What number comes next?\n\n1, 4, 9, 16, __',
    answer: '25',
    explanation: 'These are square numbers: 1², 2², 3², 4²… and 5² = 25.',
  },
  {
    id: 'odd-h1',
    category: 'odd-one-out',
    difficulty: 'hard',
    type: 'multiple-choice',
    prompt: 'Which number does not belong?',
    options: ['3', '5', '9', '11'],
    answer: '9',
    explanation: '3, 5 and 11 are prime numbers. 9 is not (it equals 3 × 3).',
  },
  {
    id: 'seq-h3',
    category: 'sequence',
    difficulty: 'hard',
    type: 'multiple-choice',
    prompt: 'What number comes next?\n\n100, 96, 88, 76, 60, __',
    options: ['40', '44', '48', '52'],
    answer: '40',
    explanation: 'The gaps grow by 4 each step (−4, −8, −12, −16, −20). After 60, subtract 20 to get 40.',
  },
]
